apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegitable-deployment
  namespace: namespace-ns

spec:
  replicas: 3
  selector:
    matchLabels:
      app: vegitable
  template:
    metadata:
      labels:
        app: vegitable
    spec:
      containers: 
      - name: vegitable-app
        image: vinothinisivakumar/vegitable-app:v1.0.1
        ports:
        - containerPort: 3000
        env:
          - name: MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: MONGODB_URI
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: PORT

