apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: {{ .Values.appService.app}}
  ports:
    - protocol: TCP
      port: {{ .Values.port}}
      targetPort: {{ .Values.port}}
  type: {{ .Values.appService.type}}
