apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-deployment
  namespace: {{ .Values.namespace}}

spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.appDeployment.labels.app}}
  template:
    metadata:
      labels:
        app: {{ .Values.appDeployment.labels.app}}
    spec:
      containers: 
      - name: {{ .Values.appDeployment.name}}
        image: {{ .Values.image.repository}}:{{ .Values.image.tag}}
        ports:
        - containerPort: {{ .Values.port}}
        env:
          - name: {{ .Release.Name }}-MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-configmap
                key: MONGODB_URI
          - name: {{ .Release.Name }}-PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-configmap
                key: PORT

