apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace}}
data:
  MONGODB_URI: {{ .Values.configmap.MONGODB_URI}}
  PORT: "{{ .Values.configmap.PORT}}"
  MONGO_INITDB_DATABASE: {{ .Values.configmap.MONGO_INITDB_DATABASE}}
