apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vegetable-app-mongo-service 
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: {{ .Values.mongoStatefulset.labels.app}}
  ports:
    - protocol: TCP
      port: {{ .Values.mongoService.port}}
      targetPort: {{ .Values.mongoPort}}
  clusterIP: {{ .Values.mongoService.clusterIP}}
