apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-veg-mongodb-pvc
  namespace: {{ .Values.namespace}}
spec:
  accessModes: {{ .Values.pvc.accessModes}}
  resources:
    requests:
      storage: {{ .Values.pvc.resources.requests.storage}}
  storageClassName: {{ .Release.Name }}-vegitable-sc
