namespace: veg-ns 

replicas: 6

appDeployment:
 labels:
  app: vegitable
 name: vegitable-conatiner

image:
 repository: vinothinisivakumar/vegitable-app
 tag: v1.0.3
port: 3000

appService:
 app: vegitable
 port: 3000
 type: LoadBalancer

configmap: 
  MONGODB_URI: "mongodb://mongodb:27017/vegetable_order_app"
  PORT: "3000"
  MONGO_INITDB_DATABASE: "myDatabase"

mongoStatefulset:
 replicas: 3
 labels:
  app: mongodb
 name: mongo-container

mongoImage: 
 repository: mongo
 tag: latest

mongoPort: 27017

mongoService:
 app: mongodb
 port: 27017
 clusterIP: None

storageclass:
 provisioner: ebs.csi.aws.com
 parameters:
  type: gp3
 reclaimPolicy: Retain 
 volumeBindingMode: WaitForFirstConsumer

pvc:
 accessModes: ["ReadWriteOnce"]
 resources:
    requests:
      storage: 2Gi  


